### ISSUE TITLE
Custom markers

### ISSUE THREAD

**Issue by cookieguru** [eclipsesource/tabris-maps#14]
It would be great to be able to customize the appearance of the marker, either by specifying the path to an image or by [providing a color](https://developers.google.com/android/reference/com/google/android/gms/maps/model/BitmapDescriptorFactory).

**Comment by mpost** [comment]
The marker api is obviously a little scarce at the moment being able to provide an image or change the color would be some obvious additions.

**Comment by hstaudacher** [comment]
+1 for allowing images

**Comment by cpetrov** [comment]
Customizing the marker image has been implemented and will be supported as of the next plugin version.
