### ISSUE TITLE
Could not listen to event "ready"

### ISSUE THREAD

**Issue by jokorivai** [eclipsesource/tabris-maps#15]
Hi, according to sample code, I created a map app with this code:
```js
new esmaps.Map({
	left: 0, right: 0, top: 0, height: 350
}).on("ready", function() {
	this.moveToPosition([-4.5248853, 129.8948361], 750);
}).appendTo(sv);
```
and got this error on log:
```
Welcome to Tabris.js
Attached to net.atm.vbn2

Could not listen to event "ready" on com.eclipsesource.maps.Map (Reason: No static method zzhi(Ljava/lang/String;)V in class Lcom/google/android/gms/common/internal/zzab; or its super classes (declaration of 'com.google.android.gms.common.internal.zzab' appears in /data/app/net.atm.vbn2-2/base.apk))
```

I used TabrisJS 1.10.0, Tabris-plugin-maps 2.0.1, cordova 6.3.0
Please advice, thanks.

**Comment by mpost** [comment]
Sounds like the bundled Google Play Services that provide the maps implementation are not of the correct version. We currently require verison `9.4.0` as you can see [here](https://github.com/eclipsesource/tabris-plugin-maps/blob/master/plugin.xml#L52).

Are you using any other plugins that require the Google Play Services?

**Comment by jokorivai** [comment]
Yes:

``` xml
<framework src="com.android.support:support-v13:23+" />
<framework src="com.google.android.gms:play-services-gcm:+" />
```

which were used on `phonegap-plugin-push` v.1.6.0
I can upgrade the `phonegap-plugin-push` plugin to current version but it is not compatible with TabrisJS (require Android 6.0+), and breaks the app.

**EDIT:**
Sorry, is `<framework src="com.google.android.gms:play-services-gcm:+" />` the same frame framework with `<framework src="com.google.android.gms:play-services-maps:9.4.0" />`?

The plugin (push plugin) also contain this line:

``` xml
<framework src="com.android.support:support-v13:23+" />
```

**Comment by mpost** [comment]
I just upgraded the maps dependency locally to the latest version `9.8.0` and the maps plugins also works as expected. There were no other plugins added at this point.

Could you make sure that you have at least the version `9.4.0` installed in your android-sdk? See `android-sdk/extras/google/m2repository/com/google/android/gms/play-services-maps`

**Comment by jokorivai** [comment]
Here are they:

![vexelindo-koleksi tutorial membuat vexel vector pixel indonesia-2016-11-08_19-14-05](https://cloud.githubusercontent.com/assets/11798147/20097075/a1670252-a5e7-11e6-9303-261a7a6c2b90.png)

**Comment by mpost** [comment]
On a note... i can reproduce the error by adding the push plugin (wich is added as `1.8.4` as the latest supported version).

**Comment by jokorivai** [comment]
So I can assume that the push plugin is (currently) not compatible with tabris map? If so, I will close this issue and wait for updates.
Thank you.

**Comment by mpost** [comment]
In its current state that is correct. Maybe they have remedied the problem in a newer update that is not yet consumed by the cordova-android platform we base tabris on. Currently that is 5.2.x

**Comment by cookieguru** [comment]
I'm going to go out on a limb and say that `com.android.support:support-v13:23+` does not play well with Tabris.js.  In order to get `phonegap-plugin-push` to work there's [eclipsesource/phonegap-plugin-push](https://github.com/eclipsesource/phonegap-plugin-push/) which [updates the support library version to 24.1.1](https://github.com/eclipsesource/phonegap-plugin-push/commit/a4547406e08cc291abce4536f7c49d01e91b0e41) and [sets the Google Play GCM version for Android to 9.2.0 instead of "latest"](https://github.com/eclipsesource/phonegap-plugin-push/commit/dc2a1bac0d05a4898f469a55a2cdc1ca3b406fa8).

**Comment by mpost** [comment]
@cookieguru Could be but since the error message points to a class inside google play services i didn't relate it to the support library. You could of course try to use the forked version: https://github.com/eclipsesource/phonegap-plugin-push
