### ISSUE TITLE
Question: How to moveToPosition of myLocation value

### ISSUE THREAD

**Issue by natanraj** [eclipsesource/tabris-maps#16]
The documentation rightly says myLocation value will not be **immediately** available.  So it shows undefined if i print.. If my pan automatically has to go my latlong, what is the best way to do so ?

it tried ...
`setTimeout(function(){
      map.moveToPosition(myPosition, 1000, {animate: true});
    }, 1500);` - Doesn't give me the desired result.

**Comment by mpost** [comment]
Currently the map widget does not have API for this task. The reason is that getting the users position is actually deprecated in the Android client. The docs state to use the location api for that. We added the deprecated property for convenience though. Currently polling like you do in your example is the best approach.

**Comment by cpetrov** [comment]
For polling you can try something in the lines of:

```js
var LOCATION_GIVE_UP_TIMEOUT = 10000;
var LOCATION_CHECK_INTERVAL = 100;

var map; // your map
var locationGiveUpTimeout;
var locationGiveUp;

function getCurrentLocation() { // returns a Promise resolving with a location or null
  if (!locationGiveUpTimeout) {
    locationGiveUpTimeout = setTimeout(function() {
      locationGiveUp = true;
    }, LOCATION_GIVE_UP_TIMEOUT);
  }
  return new Promise(function(resolve) {
    let location = map.get('myLocation');
    if (locationGiveUp) {
      locationGiveUp = false;
      return resolve(null);
    }
    if (!location) {
      return setTimeout(function() {
        resolve(getCurrentLocation());
      }, LOCATION_CHECK_INTERVAL);
    }
    if (location) {
      resolve(location);
      clearTimeout(locationGiveUpTimeout);
      locationGiveUpTimeout = null;
    }
  });
}
```

**Comment by natanraj** [comment]
Hey @cpetrov ; thanks a lot. This works like charm. I guess we need to add this to our examples and very useful.
