### ISSUE TITLE
Support Google Maps on iOS

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-maps#2]
Support Google Maps on iOS

like this cordova plugin:
https://github.com/wf9a5m75/phonegap-googlemaps-plugin

**Comment by jonek** [comment]
As also mentioned in this project's [README.md](https://github.com/eclipsesource/tabris-maps/blob/master/README.md), our plan with this plugin is to provide maps support for iOS based on [Map Kit framework](https://developer.apple.com/maps/). 
"It provides access to features available through the Map Kit framework on iOS and the Google Maps API on Android."
Thus this custom widget would provide an abstraction of both platform's native map features.

Would that also provide the features you need, or do you require specific features only available through the [Google Maps SDK for iOS](https://developers.google.com/maps/documentation/ios-sdk)?

**Comment by mpost** [comment]
Currently not in scope for this project.
