### ISSUE TITLE
esmaps is not defined. What is esmaps?

### ISSUE THREAD

**Issue by CooperWolfe** [eclipsesource/tabris-maps#25]
My config.xml file is here: `<?xml version='1.0' encoding='utf-8'?>
<widget id="abc.def.ghi" version="0.1.0">
 <name>Abc</name>
  <description>
    Abc Def Ghi!
  </description>
  <author email="abc@def.ghi">
    Abc Def
  </author>
  <plugin name="tabris-plugin-maps" spec="https://github.com/eclipsesource/tabris-plugin-maps">
    <variable name="ANDROID_API_KEY" value="AbcdEfG1hijK2LM3NO-P4Qr5STUvw6Yz7abcdeF" />
  </plugin>
</widget>`

I have also `npm install tabris-plugin-maps` but it has no main in the package.config so I can't `require()` it.

I would love to start using this plugin but it seems I just cannot. It always comes back to `esmaps is not defined` so what exactly is esmaps and why is it assumed to be declared in all of the documentation. And why is it not in mine?

**Comment by cookieguru** [comment]
The Readme has a typo in it and should read:
```xml
<plugin name="tabris-plugin-maps" spec="https://github.com/eclipsesource/tabris-plugin-maps.git">
```
(note the `.git` at the end).  Once you've added this, build your app again.

BTW: esmaps = EclipseSource Maps

**Comment by CooperWolfe** [comment]
Okay, so you must build in order for this to work? If that's the case then is there any better way of testing?

**Comment by cookieguru** [comment]
Yes, you must build.  Building is the only way to add additional native code to an app, so there is no better way of testing.

**Comment by CooperWolfe** [comment]
Wow. Well that kind of sucks. Thank you for your help. And one more thing: do you have any idea where I can find out when/where this feature will be added to tabris itself?

**Comment by cookieguru** [comment]
Why does that suck?

The answer to your second question is probably never, for several reasons:

1. It keeps the main framework lightweight
2. It makes it easier to enhance the maps feature without forcing an upgrade to Tabris.js
3. It serves as an example project as to how others can develop their own custom plugins to leverage native code from the JS

**Comment by CooperWolfe** [comment]
Those are all fair reasons, but it sucks because building takes a lot longer. I am exploring my options for cross-platform development for an app I am making that will need Map capabilities. If I have to build for every test it may not be worth using. But I'm still looking around.

**Comment by cookieguru** [comment]
You don't need to build for every test.  Quoting [the docs](https://tabrisjs.com/documentation/latest/build#settings):
> If [debug mode is] set to ON, your app will be built including debug symbols and it will be packaged into the Tabris.js Developer App to make development easier. This allows you to use all the benefits like the developer console or the reload also with your own app.

While developing your app, the only time you need to build is when you're modifying the native code.  Usually this just means installing or updating plugins.  With a debug app, you can reload your source code from your development machine with the tap of a button.

**Comment by CooperWolfe** [comment]
Oh wow! I apologize for my incompetence but how do I set debug mode ON?

**Comment by cookieguru** [comment]
Are you using local build or cloud build?  For cloud build, refer to my last link.  For local builds, just pass the `--debug` parameter when building.

**Comment by CooperWolfe** [comment]
Local. Thank you very much, cookieguru. You are a guru indeed.

**Comment by mpost** [comment]
@cookieguru Thanks for pointing out the missing ".git" extension in the README. We have updated it accordingly.
