### ISSUE TITLE
Marker-Images seem to be rendered much smaller on Android than on iOS

### ISSUE THREAD

**Issue by samynomad** [eclipsesource/tabris-maps#49]
### Problem description

Using the same icons for markers without defining a scale factor, the placeholders on iOS are much bigger than on Android. 

### Expected behavior

Icons should look the same no matter what environment is used.

### Environment

- Maps Plugin `backport-marker-images-to-3.0` branch
- Tabris.js version: 2.1.1.
- Device: iPhone6 plus and Samsung Galaxy J5 (2016)
- OS:  iOS 11.x and Android 7.1.1

**Comment by samynomad** [comment]
Example: 

![grafik](https://user-images.githubusercontent.com/1726398/35765969-2912108e-08cf-11e8-9a6d-3356f9d755c0.png)

**Comment by cpetrov** [comment]
Fixed in 4.0.1
