### ISSUE TITLE
Map tiles not correctly loaded when setting "center"

### ISSUE THREAD

**Issue by jonek** [eclipsesource/tabris-maps#5]
Steps to reproduce:
1. start tabris-maps-example
2. zoom into the map until you can see the "SYDNEY TOWER" location marker
3. select the "Go to Blacktown" button
4. now the map only shows a grid and no tiles are loaded
5. now you can alternate locations via the "Go to Sydney" and "Go to Blacktown" buttons - Sydney shows map tiles, Blacktown doesn't

**Comment by mpost** [comment]
Could not reproduce. Closing. Please reopen when the issue persists.
