### ISSUE TITLE
Disallowing location access

### ISSUE THREAD

**Issue by cookieguru** [eclipsesource/tabris-maps#58]
In `config.xml` I have the following line:
```xml
<hook type="before_compile" src="remove_location_permission.js" />
```
Which runs the following code:
```js
#!/usr/bin/env node
const fs = require('fs');

if(fs.existsSync('platforms/android')) {
	let lines = fs.readFileSync('platforms/android/AndroidManifest.xml', 'utf8').split('\n');
	const MANIFEST = 'platforms/android/AndroidManifest.xml';

	lines.forEach((line, index, object) => {
		if(line.match(/ACCESS_COARSE_LOCATION|ACCESS_FINE_LOCATION/)) {
			object.splice(index, 1);
		}
	});

	fs.writeFileSync(MANIFEST, lines.join('\n'));
}
```

I have inspected the output that gets sent to `writeFileSync` and it does not contain any lines regarding location access permissions.  However the built APK still requests permission `ACCESS_FINE_LOCATION`, as seen by the toggle switch in the app's permission in system settings as well as the somewhat obfuscated `AndroidManifest.xml` in the release APK.

I don't need the user's location at all in this app; is there a better way to remove this permission?

**Comment by mpost** [comment]
I presume the permission is added by some plugin which might need the permissions. Otherwise changing that plugin could be an option.

**Comment by cookieguru** [comment]
The only other plugin I'm using is `cordova-plugin-globalization`

**Comment by mpost** [comment]
I would not be aware of how else this permissions could be added into an application. If you create a vanilla tabris app it only requires the network permission (which can not be toggled by the user). Are you sure there are no other plugins? Maybe any transitive dependencies?

**Comment by cookieguru** [comment]
@mpost I created a test project with just this plugin and determined that the issue was the `forEach` statement iterating differently than I expected.  Simplifying that snippet to just use a string solved it.  Will submit #59 to add this to the docs for anyone else that might want to display maps but not access the user's location.

**Comment by mpost** [comment]
@cookieguru Thanks for the heads up.
