### ISSUE TITLE
Can't build with 3.0

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-maps#60]
I just tried to build example. Error log: https://pastebin.com/r3ftSneM

**Comment by mpost** [comment]
How did you include the plugin?

**Comment by mpost** [comment]
The maps plugin is not yet compatible with Tabris 3.0. See README. 

> Compatible with Tabris.js 2.4 and 2.5.

We will update it in the next few days.

**Comment by mpost** [comment]
In fact we have just updated the master branch with an android version that is 3.0 compatible.

**Comment by fax1ty** [comment]
App crashed when I appended it to `Page`. Is it working only with `contentView`? 
Error log: https://pastebin.com/JQc8Rakv
I can run ADB and give a full log from Logcat if necessary

**Comment by mpost** [comment]
Closing as resolved.
