### ISSUE TITLE
Problems after clean project import

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-maps#63]
![image](https://user-images.githubusercontent.com/26363214/64065183-56906e00-cc1b-11e9-89a9-0926d3b369a1.png)
https://github.com/eclipsesource/tabris-plugin-maps/blob/f573665834d1ca66f088c3f3d49bc95382f00e95/src/android/com/eclipsesource/tabris/maps/CameraProperty.kt#L14
![image](https://user-images.githubusercontent.com/26363214/64065201-893a6680-cc1b-11e9-9941-0e3222713e9c.png)

https://github.com/eclipsesource/tabris-plugin-maps/blob/f573665834d1ca66f088c3f3d49bc95382f00e95/src/android/com/eclipsesource/tabris/maps/MapHolderView.kt#L40
![image](https://user-images.githubusercontent.com/26363214/64065191-7031b580-cc1b-11e9-9302-e442561ae78c.png)

**Comment by mpost** [comment]
Compile errors for tabris `nightly` builds have been resolved via https://github.com/eclipsesource/tabris-plugin-maps/commit/b8a06c476a859a409a300ac24f1cfde9a20a43c5.
