### ISSUE TITLE
Is Map appendable to Tab?

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-maps#64]
Can I append it to `Tab`? 
I just got nothing after appending it to `Tab`

**Comment by cookieguru** [comment]
Works for me in 2.8.1:

```js
const tabFolder = new tabris.TabFolder({
	left: 0, top: 0, right: 0, bottom: 0,
}).appendTo(tabris.ui.contentView);

const tab = new tabris.Tab({
	title: 'Map',
}).appendTo(tabFolder);

new tabris.Tab({
	title: 'Blank',
}).appendTo(tabFolder);

new esmaps.Map({
	top: 0, left: 0, right: 0, bottom: 0,
}).appendTo(tab);
```

**Comment by fax1ty** [comment]
> Works for me in 2.8.1:

Your code breaks 3.1 app. 

```
const tabFolder = new TabFolder({
    left: 0, top: 0, right: 0, bottom: 0,
}).appendTo(contentView);

const tab = new Tab({
    title: 'Map',
}).appendTo(tabFolder);

new Tab({
    title: 'Blank',
}).appendTo(tabFolder);

new esmaps.Map({
    top: 0, left: 0, right: 0, bottom: 0,
}).appendTo(tab);
```
Will cause https://pastebin.com/idm9YiNK

**Comment by fax1ty** [comment]
@cookieguru Oh, I do this 

```js
const tab = new Tab({
    title: 'Map',
}).appendTo(tabFolder)
    .onAppear(({ target: t }) => {
        new esmaps.Map({
            top: 0, left: 0, right: 0, bottom: 0,
        }).appendTo(t);
    });
```
and it helped
But want clarify. Is it normal behavior for `appear` not to fire when the `tab` first appears?

**Comment by fax1ty** [comment]
Hmm even if I'll `trigger()` `Tab`'s `appear` event it will lead to https://pastebin.com/idm9YiNK

**Comment by fax1ty** [comment]
and this
```js
new esmaps.Map({
    top: 0, left: 0, right: 0, bottom: 0
}).appendTo($('#tab').first())
```

**Comment by cookieguru** [comment]
>  But want clarify. Is it normal behavior for `appear` not to fire when the `Tab` first appears?

I believe to get the intended effect you'll want to add the listener before it is appended to its parent; that way the listener is registered on object creation.  Likely the `appear` event *is* firing, it just fires slightly before you attach the listener to it.

**Comment by fax1ty** [comment]
Yeah, problem exactly in appending it to `Fragment` before fragment will be fully ready
