### ISSUE TITLE
Marker cannot use any image

### ISSUE THREAD

**Issue by fax1ty** [eclipsesource/tabris-maps#65]
### Problem description
I create marker with picture, but the picture is not drawn, instead it is a standard red marker
I built an example app and got the following

![image](https://user-images.githubusercontent.com/26363214/68582582-861deb00-0494-11ea-911c-6a5a8b2e6586.png)

### Expected behavior
![image](https://user-images.githubusercontent.com/26363214/68582546-73a3b180-0494-11ea-85cc-fd37da9d2ec7.png)

### Environment

- Tabris.js version: 3.2.1
- Device: Xiaomi Redmi 5 Plus
- OS: Android 9

### Code snippet
https://github.com/eclipsesource/tabris-plugin-maps/blob/46b47fc2b620633e9e399a601e6418a292b787d6/.example/src/pages/MarkerPage.js#L36-L40

**Comment by elshadsm** [comment]
The issue with not displayed marker image has been solved via 05e526b.
